### ISSUE TITLE
Integrate Typescript with build system remaining tasks

### ISSUE THREAD

**Issue by drewatk** [drewatk/backtrack#2]
### Tasks:

- [ ] Use https://www.npmjs.com/package/fork-ts-checker-webpack-plugin to fail Webpack builds when typescript errors
- [ ] Integrate Tslint into build steps
- [ ] Integrate Typescript into Travis builds
- [ ] Validate React hot reloading works on `yarn dev`
